package hiber;
// Generated Dec 16, 2016 11:33:55 PM by Hibernate Tools 4.3.1



/**
 * Carddetail generated by hbm2java
 */
public class Carddetail  implements java.io.Serializable {


     private int psgId;
     private String cardNumber;
     private String cardName;
     private String expMonth;
     private String expYear;

    public Carddetail() {
    }

    public Carddetail(int psgId, String cardNumber, String cardName, String expMonth, String expYear) {
       this.psgId = psgId;
       this.cardNumber = cardNumber;
       this.cardName = cardName;
       this.expMonth = expMonth;
       this.expYear = expYear;
    }
   
    public int getPsgId() {
        return this.psgId;
    }
    
    public void setPsgId(int psgId) {
        this.psgId = psgId;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public String getCardName() {
        return this.cardName;
    }
    
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }
    public String getExpMonth() {
        return this.expMonth;
    }
    
    public void setExpMonth(String expMonth) {
        this.expMonth = expMonth;
    }
    public String getExpYear() {
        return this.expYear;
    }
    
    public void setExpYear(String expYear) {
        this.expYear = expYear;
    }




}


